# Istio install instruction https://istio.io/latest/docs/setup/install/helm/

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: istiod
spec:
  project: default
  source:
    repoURL: "https://istio-release.storage.googleapis.com/charts"
    path: ""
    # MANUAL_UPDATE: https://artifacthub.io/packages/search?org=istio
    targetRevision: 1.16.0-beta.2
    chart: istiod
  destination:
    name: ""
    namespace: istio-system
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
