kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - gateway.yaml
  - service.yaml
  - deployment.yaml
  - cert-manager-application.yaml
  - istio-application.yaml
  - istiod-application.yaml
